[platformio]
default_envs = arduino-pro-micro
src_dir = src
include_dir = include
lib_dir = lib
test_dir = test

[env]
monitor_speed = 250000
monitor_filters = time, default, printable
lib_deps =
	NicoHood/HID-Project@^2.8.4


[env:arduino-pro-micro]
platform = atmelavr
;board = sparkfun_promicro16
board = micro
framework = arduino
build_flags =
  -D TARGET_ARDUINO_PRO_MICRO
  -D USB_VID=0x256F
  -D USB_PID=0xC631
  
board_build.vid = 0x256F
board_build.pid = 0xC631
board_build.usb_manufacturer = 3Dconnexion
board_build.usb_product = Spacemouse Micro
upload_resetmethod = manual
monitor_speed = 250000

[env:rp2040]
platform = raspberrypi
board = pico
framework = arduino
build_flags =
  -D TARGET_RP2040
  -D HES_PIN_0=26
  -D HES_PIN_1=27
  -D HES_PIN_2=28
  -D HES_PIN_3=29
  -D HES_PIN_6=26
  -D HES_PIN_7=27
  -D HES_PIN_8=28
  -D HES_PIN_9=29
  -D BTN_PIN_0=0
  -D BTN_PIN_1=1
  -D BTN_PIN_2=2

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
build_unflags =
  -D ARDUINO_USB_MODE=1
build_flags =
  -D TARGET_ESP32S3
  -D ARDUINO_USB_MODE=0
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D HES_PIN_0=1
  -D HES_PIN_1=2
  -D HES_PIN_2=3
  -D HES_PIN_3=4
  -D HES_PIN_6=5
  -D HES_PIN_7=6
  -D HES_PIN_8=7
  -D HES_PIN_9=8
  -D BTN_PIN_0=9
  -D BTN_PIN_1=10
  -D BTN_PIN_2=11

[env:native]
platform = native
test_build_src = yes
build_flags =
  -D UNIT_TEST
build_src_filter =
  -<*>
  +<Buttons.cpp>
  +<Motion.cpp>
  +<Settings.cpp>
